---
version: '3.42.1'

dotenv: ['.env']

vars:
  COMPOSE_SERVICE: 'github-metrics-exporter'

includes:
  cleanup: .task/cleanup/taskfile.yml
  common: .task/common/taskfile.yml
  copilot: .github/skills/taskfile.yml
  go: src/taskfile.yml

tasks:

  symlinks:
    desc: Create symlinks for shared files
    cmds:
      - ln -sf "$(pwd)/.github/copilot-instructions.md" "$(pwd)/CLAUDE.md"
      - ln -sf "$(pwd)/.github/instructions/go.instructions.md" "$(pwd)/src/CLAUDE.md"

  lint:
    desc: Run all project linters outside of Dockerfile linters
    cmds:
      - task: cleanup:filesystem
      - task: go:cleanup
      - task: symlinks
      - for: ['yaml', 'workflows', 'filenames', 'folders', 'gherkin', 'markdown-links']
        cmd: docker compose up lint-{{ .ITEM }} --exit-code-from lint-{{ .ITEM }}
      - task: go:complexity
      - task: go:licenses
      - task: go:lint

  # ===============================================================================================

  docker:build:
    desc: Lint and build container COMPOSE_SERVICE
    cmds:
      - docker compose up {{ .COMPOSE_SERVICE }}-lint-dockerfile --exit-code-from {{ .COMPOSE_SERVICE }}-lint-dockerfile
      - docker compose build {{ .COMPOSE_SERVICE }}

  docker:run:
    desc: Run container COMPOSE_SERVICE
    cmds:
      - docker compose up {{ .COMPOSE_SERVICE }}
